### ISSUE TITLE
bot tries to edgeguard the wrong edge

### ISSUE THREAD

**Issue by geranim0** [altf4/SmashBot#43] opened 2016-02-14 02:14 UTC
I don't know when but sometimes fox will edgeguard the wrong one

**Comment by altf4** [comment] 2016-02-14 06:51
You mean Fox runs to the opposite side of FD and edge guards the completely wrong side? I haven't observed that before... Try to find a way to reproduce it, or else record it happening. (You can use Dolphin's frame dumping feature if you don't mind a bit of slowness)

**Comment by XeSquirmy** [comment] 2016-02-14 07:07
Just to add on as well, I've never seen this issue happen before as well. It'd be neat if you could reproduce it or give steps to be able to.

**Comment by geranim0** [comment] 2016-02-15 14:04
ledge stall ledge jump reverse nair, fsmash fox upb and camp the other ledge. when fox will recover on the stage he will edgeguard the wrong one.

**Comment by XeSquirmy** [comment] 2016-02-15 23:09
I was able to reproduce the bug, here's a link to a video of it.

[https://www.youtube.com/watch?v=ZbXLN8phIG0](https://www.youtube.com/watch?v=ZbXLN8phIG0)

**Comment by spxtr** [comment] 2016-02-16 00:18
That's really funny.

**Comment by altf4** [comment] 2016-02-16 03:10
Nice work! Fox was choosing the edge closest to HIM, not the one the opponent is actually on. 

I'll accept your pull request since it's definitely an improvement, but it's not a complete fix. In that situation, Fox shouldn't even be in the edgeguard tactic at all. If the enemy is that far away, we should just be lasering.

**Comment by altf4** [comment] 2016-03-30 06:00
I think we can call this fixed by now. There's been a lot of incremental improvement around edgeuarding.

**Closed by altf4** 2016-03-30 06:00 UTC
